### ISSUE TITLE
When to publish the code？

### ISSUE THREAD

**Issue by HuiFHub** [FuxiVirtualHuman/styletalk#1]
Amazing work!
When do you plan to publish the code? Or the inference code and weights should be public for comparison. Thanks!

**Comment by lostork** [comment]
Thanks for your attention.
We are organizing our code and will release the code as early as February 2023, possibly a little later.  
Sorry for the delay.

**Comment by altryne** [comment]
Let us know if you want beta testers :)

**Comment by primepake** [comment]
very exciting!

**Comment by Hothin** [comment]
> 

Awesome! do you plan to publish the train code? I want to train my model

**Comment by Hothin** [comment]
> Thanks for your attention. We are organizing our code and will release the code as early as February 2023, possibly a little later. Sorry for the delay.

Awesome! do you plan to publish the train code? I want to train my model

**Comment by arvintashakori** [comment]
Great work! I want to train my model as well! please publish the train code as well!

**Comment by maggiez0138** [comment]
Awesome! Looking forward to playing around the training and inference part.

**Comment by xiaoqian-shen** [comment]
Great work! Looking forwards to the released code! Hope it will be published in early February.

**Comment by ueumd** [comment]
期待！

**Comment by rbychn** [comment]
When is it coming? Eagerly waiting!

**Comment by xiaoquan-serien** [comment]
Great work! Looking forwards to the released code! Hope it will be published in early February.
But now, it is in lately February

**Comment by Perseus1993** [comment]
awesome,chop chop!

**Comment by dn-bit** [comment]
please upload code now

**Comment by huangxin168** [comment]
Amazing！
Waiting for your code.

**Comment by FuxiVirtualHuman** [comment]
Already released
