### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

### ISSUE THREAD

**Issue by G-force78** [FuxiVirtualHuman/styletalk#16]
Hi, I have added my own wav file (16k, pcm, 16000hz) and get this error. 

Traceback (most recent call last):
  File "/content/styletalk/inference_for_demo.py", line 168, in <module>
    generate_expression_params(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/styletalk/inference_for_demo.py", line 107, in generate_expression_params
    audio_win = torch.tensor(audio_win).cuda()
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
video created!

OK so it wasnt the wav file it was the json not being in the correct format.

**Comment by G-force78** [comment]
After extracting phonemes with allosauras https://github.com/xinjli/allosaurus.git

You can use claude2 to convert to CMU

OR

You can use this to convert to CMU https://github.com/morevnaproject-org/papagayo-ng/blob/master/phoneme_conversion_helper.py

Then from CMU to indices 

```
import json

# Given phoneme index
phoneme_index = {
    "AA": 0, "AE": 1, "AH": 2, "AO": 3, "AW": 4, "AY": 5, "B": 6, "CH": 7, "D": 8, "DH": 9,
    "EH": 10, "ER": 11, "EY": 12, "F": 13, "G": 14, "HH": 15, "IH": 16, "IY": 17, "JH": 18,
    "K": 19, "L": 20, "M": 21, "N": 22, "NG": 23, "NSN": 24, "OW": 25, "OY": 26, "P": 27,
    "R": 28, "S": 29, "SH": 30, "SIL": 31, "T": 32, "TH": 33, "UH": 34, "UW": 35, "V": 36,
    "W": 37, "Y": 38, "Z": 39, "ZH": 40
}

# Read the original JSON data from a file
with open('/content/styletalk/your_file.json') as f:
    json_data = json.load(f)


# Convert phoneme labels to phoneme indices
for item in json_data:
    for phone in item['phones']:
        phone['ph'] = phoneme_index[phone['ph']]

# Save the converted JSON data as a new file
with open('converted_file.json', 'w') as f:
    json.dump(json_data, f, indent=4)

print("Converted JSON data has been saved")
```
Then strip it down to just the values

```
#@title once phonemes have been converted from IPA to CMU 
import json

# Read the JSON data from the file
with open('/content/styletalk/converted_file.json') as f:
    json_data = json.load(f)

# Extract only the "ph" values
ph_values = [phone["ph"] for item in json_data for phone in item["phones"]]

# Save the new JSON data as a file
with open('usablefile_seq.json', 'w') as f:
    json.dump(ph_values, f, separators=(',', ':'))

print("New JSON data has been saved")
```

Code was thanks to chatGPT at you.com

**Comment by QUTGXX** [comment]
@G-force78 Can u share us how to extract the phonemes?

**Comment by G-force78** [comment]
> @G-force78 Can u share us how to extract the phonemes?

I used https://github.com/xinjli/allosaurus.git
