### ISSUE TITLE
what is your planning about releasing code 

### ISSUE THREAD

**Issue by dn-bit** [FuxiVirtualHuman/styletalk#4]
hi sir,

as i have seen above you tell that code release on feb 2023,but now march also gone so please upload code as soon as possible

Thanks ,public is waiting for your code please release as soon as possible

**Comment by arvintashakori** [comment]
We are waiting for the code. It's April 2023 but we haven't received an update yet?

**Comment by jinfagang** [comment]
@FuxiVirtualHuman Would like release the code as well. Please release the code as you announced earlier.

**Comment by FuxiVirtualHuman** [comment]
already released
